### ISSUE TITLE
IPv6 Support to Lycoris

### ISSUE THREAD

**Issue by TheKoakuma** [0x00000FF/Lycoris#1]
Does have any way to give IPv6 support to Lycoris? Is becoming quite hard to get an ISP who doesn't use CGNAT with public IPv6 but private IPv4

Idk if is just change the ipv4 (x.x.x.x:10080) to ipv6 under brackets ([xxxx : xxxx ::::: xxxx : xxxx]:10080), but i think that's a valid improvement to adonis

**Comment by 0x00000FF** [comment]
This project is currently suspended due to schedule, but will be resumed soon!

I will consider about that. Thank you for opening issue and suggestion!
